export const gstFields = [
  { label: "S.No", key: "s_no" },
  { label: "Type", key: "" },
  { label: "SourceIdentifier", key: "" },
  { label: "SourceFileName", key: "" },
  { label: "GLAccountCode", key: "" },
  { label: "Division", key: "" },
  { label: "SubDivision", key: "" },
  { label: "ProfitCentre1", key: "" },
  { label: "ProfitCentre2", key: "" },
  { label: "PlantCode", key: "" },
  { label: "ReturnPeriod", key: "" },
  { label: "Supplier GSTIN ", key: "invoice_no" },
  { label: "DocumentType", key: "" },
  { label: "SupplyType", key: "" },
  { label: "DocumentNumber (Invoice no)", key: "" },
  { label: "DocumentDate", key: "" },
  { label: "OriginalDocumentNumber", key: "" },
  { label: "OriginalDocumentDate", key: "" },
  { label: "CRDRPreGST", key: "" },
  { label: "LineNumber", key: "" },
  { label: "Customer GSTIN", key: "" },
  { label: "UINorComposition", key: "" },
  { label: "OriginalCustomerGSTIN", key: "" },
  { label: "Customer Name", key: "customer_name" },
  { label: "Customer Code", key: "customer_auth_code" },
  { label: "BillToState", key: "" },
  { label: "ShipToState", key: "" },
  { label: "POS", key: "" },
  { label: "PortCode", key: "" },
  { label: "ShippingBillNumber", key: "" },
  { label: "ShippingBillDate", key: "" },
  { label: "FOB", key: "" },
  { label: "ExportDuty", key: "" },
  { label: "HSNorSAC", key: "" },
  { label: "ProductCode", key: "" },
  { label: "ProductDescription", key: "" },
  { label: "CategoryOfProduct", key: "" },
  { label: "UnitOfMeasurement", key: "" },
  { label: "Quantity", key: "" },
  { label: "Taxable Value", key: "" },
  { label: "IntegratedTaxRate", key: "igst" },
  { label: "IntegratedTaxAmount", key: "igst_amt" },
  { label: "CentralTaxRate", key: "cgst" },
  { label: "CentralTaxAmount", key: "cgst_amt" },
  { label: "StateUTTaxRate", key: "sgst" },
  { label: "StateUTTaxAmount", key: "sgst_amt" },
  { label: "CessRateAdvalorem", key: "" },
  { label: "CessAmountAdvalorem", key: "" },
  { label: "CessRateSpecific", key: "" },
  { label: "CessAmountSpecific", key: "" },
  { label: "InvoiceValue", key: "" },
  { label: "ReverseChargeFlag", key: "" },
  { label: "TCSFlag", key: "" },
  { label: "eComGSTIN", key: "" },
  { label: "ITCFlag", key: "" },
  { label: "ReasonForCreditDebitNote", key: "" },
  { label: "AccountingVoucherNumber", key: "" },
  { label: "AccountingVoucherDate", key: "" },
  { label: "Userdefinedfield1", key: "" },
  { label: "Userdefinedfield2", key: "" },
  { label: "Userdefinedfield3", key: "" },
  { label: "GL Code", key: "" },
  { label: "Remarks", key: "" },
];
