export const inventoryFields = [
    { label: "S.No.", key: "s_no" },
    { label: "Assign", key: "active2" },
    { label: "SKU Name", key: "sku_name" },
    { label: "SKU Name Kannada", key: "sku_name_kannada" },
    { label: "SKU code", key: "sku_code" },
    { label: "Category", key: "category_name" },
    { label: "Sub Category", key: "subcategory_name" },
    { label: "Weight", key: "weight" },
    { label: "MRP", key: "mrp" },
    { label: "Price(Default)", key: "price" },
    { label: "Sale Price(Set By You)", key: "sale_price" },
    { label: "Package", key: "package" },
    { label: "UPC", key: "units_per_case" },
    { label: "Dimension", key: "dimension" },
    { label: "Brand", key: "brand_name" },
    { label: "SGST", key: "sgst" },
    { label: "CGST ", key: "cgst" },
    { label: "IGST ", key: "igst" },
    { label: "Total Quantity ", key: "quantity" },
    { label: "Used Quantity ", key: "used_quantity"},
    { label: "Quantity in Stock ", key: "qty_in_stock"},
  ];