export const marginFields = [
  { label: "S.No", key: "s_no" },
  { label: "Order ID", key: "main_order_no" },
  { label: "Suborder No", key: "suborder_no" },
  { label: "Order Date", key: "order_date" },
  { label: "Farmer Name", key: "customer_name" },
  { label: "Brand", key: "brand_name" },
  { label: "Category", key: "category_name" },
  { label: "Sub_category", key: "subcategory_name" },
  { label: "SKU_Placed", key: "sku_name" },
  { label: "SKU_Code", key: "sku_code" },
  { label: "SKU_Size", key: "weight" },
  { label: "Quantity", key: "quantity" },
  { label: "Unit_Price ", key: "price" },
  { label: "SGST", key: "sgst" },
  { label: "SGST Amt", key: "sgst_amt" },
  { label: "CGST ", key: "cgst" },
  { label: "CGST Amt", key: "cgst_amt" },
  { label: "IGST", key: "igst" },
  { label: "IGST Amt", key: "igst_amt" },
  { label: "Total Tax Value", key: "tax_amount" },
  { label: "Total Taxable Value", key: "net_amount" },
  { label: "Coupon Code", key: "boucher_code" },
  { label: "Coupon Amount", key: "boucher_amount" },
  { label: "Cargill Margin(Amt.)", key: "cargill_margin_amount" },
  { label: "Cargill Margin(%)", key: "cargill_margin" },
  { label: "Total Value", key: "total_price" },
];
